<?php
include_once 'dbconfig.php';

if(isset($_GET['view_id']))
{
 $sql_query="SELECT * FROM aliados_pro WHERE id=".$_GET['view_id'];
 $result_set=mysqli_query($con,$sql_query);
 $fetched_row=mysqli_fetch_array($result_set,MYSQLI_ASSOC);
}
?>


<!DOCTYPE html>
<html lang="en">
<head>
  <title>Core PHP CRUD functions generated By PHP Code Builder</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>

<div class="container mt-3">
  <h2>Core PHP CRUD functions generated By <a href="http://www.phpcodebuilder.com" target="_blank">By PHP Code Builder</a></h2>
 
  
  <div class="table-responsive">
    <table class="table table-bordered">
   <tr>
    <td>
   <label for="name" class="form-label">Name:</label>
   </td>
   <th colspan="5"> <?php echo $fetched_row['name'] ?></th>
</tr>
 <tr>
    <td>
   <label for="alt_image" class="form-label">Alt_image:</label>
   </td>
   <th colspan="5"> <?php echo $fetched_row['alt_image'] ?></th>
</tr>
 <tr>
    <td>
   <label for="Orden" class="form-label">Orden:</label>
   </td>
   <th colspan="5"> <?php echo $fetched_row['Orden'] ?></th>
</tr>
 <tr>
    <td>
   <label for="link" class="form-label">Link:</label>
   </td>
   <th colspan="5"> <?php echo $fetched_row['link'] ?></th>
</tr>
 </table>
 </div>
</div>
</body>
</html>
